name: Homebox
slug: homebox
description: 'Inventory and organization system built for the Home User'
version: 0.21.0
url: https://github.com/sysadminsmedia/homebox
logo: https://raw.githubusercontent.com/Oddiesea/homebox-ingress-ha-addon/main/homebox/logo.png
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 7745
panel_icon: mdi:package-variant
panel_title: Homebox
init: false
startup: services
boot: auto
map:
  - config:rw
ports:
  "7745/tcp": null
ports_description:
  "7745/tcp": "Web interface (Ingress)"
options:
  allow_registration: true
  auto_increment_asset_id: true
  web_max_upload_size: 10
  web_read_timeout: 10
  web_write_timeout: 10
  web_idle_timeout: 30
  mailer_host: ''
  mailer_port: 587
  mailer_username: ''
  mailer_password: ''
  mailer_from: ''
schema:
  allow_registration: bool?
  auto_increment_asset_id: bool?
  web_max_upload_size: int(1,1000)?
  web_read_timeout: int(1,300)?
  web_write_timeout: int(1,300)?
  web_idle_timeout: int(1,600)?
  mailer_host: str?
  mailer_port: int(1,65535)?
  mailer_username: str?
  mailer_password: str?
  mailer_from: str?
image: ghcr.io/oddiesea/home-assistant-homebox-{arch}

